apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deployment
spec:
 selector:
   matchLabels:
    type: webn
    app: backend
    version: vlatest
 replicas: 2
 template:
   metadata:
     labels:
       type: webn
       app: backend
       version: vlatest
   spec:
    containers:
    - name: backend
      image: shtnfo/backend:latest
      envFrom:
        - configMapRef:
            name: mysql-cm
        - secretRef:
            name: mysql-sec
      ports:
      - containerPort: 8000
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m